import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  isHttpMode as harnessIsHttpMode,
  isStdioMode as harnessIsStdioMode,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
  type McpHttpServerHandle,
} from "@hasna/mcp-harness";
import {
  startMcpHttpServer as harnessStartMcpHttpServer,
} from "@hasna/mcp-harness/node";

/**
 * open-mementos MCP transport/port boilerplate — thin shim over @hasna/mcp-harness.
 * Public API preserved; hand-rolled transport/port/health removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 */

export const MCP_HTTP_SERVICE_NAME = "mementos";
export const DEFAULT_MCP_HTTP_PORT = 8867;

export type { McpHttpServerHandle };
export function isHttpMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsHttpMode(argv, env);
}
export function isStdioMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsStdioMode(argv, env);
}
export function resolveMcpHttpPort(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): number {
  return harnessResolveMcpHttpPort({ argv, env, default: DEFAULT_MCP_HTTP_PORT });
}
export async function startMcpHttpServer(
  buildServer: () => McpServer,
  options?: { port?: number; host?: string; serviceName?: string },
) {
  return harnessStartMcpHttpServer(buildServer, {
    port: options?.port,
    host: options?.host,
    serviceName: options?.serviceName ?? MCP_HTTP_SERVICE_NAME,
    defaultPort: DEFAULT_MCP_HTTP_PORT,
  });
}
